### ISSUE TITLE
mod crashed the game ... :(

### ISSUE THREAD

**Issue by MSandro** [JSJBDEV/SuperCobblestoneFunnels#5]
sometimes my single player map crashes because of this mod...

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 6/12/21 11:39 PM
Description: Exception while ticking

java.lang.ArrayIndexOutOfBoundsException: 9
	at gd.rf.acro.scf.CobblestoneFunnelBlock.getOreFromBigNumber(CobblestoneFunnelBlock.java:169)
	at gd.rf.acro.scf.CobblestoneFunnelBlock.method_9588(CobblestoneFunnelBlock.java:64)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:874)
	at net.minecraft.class_3218.method_14189(class_3218.java:602)
	at net.minecraft.class_3218$$Lambda$7708/867710887.accept(Unknown Source)
	at net.minecraft.class_1949.method_8670(class_1949.java:84)
	at net.minecraft.class_3218.method_18765(class_3218.java:357)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7681/2096723395.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at gd.rf.acro.scf.CobblestoneFunnelBlock.getOreFromBigNumber(CobblestoneFunnelBlock.java:169)
	at gd.rf.acro.scf.CobblestoneFunnelBlock.method_9588(CobblestoneFunnelBlock.java:64)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:874)
	at net.minecraft.class_3218.method_14189(class_3218.java:602)
	at net.minecraft.class_3218$$Lambda$7708/867710887.accept(Unknown Source)

-- Block being ticked --
Details:
	Block location: World: (-8,65,6), Chunk: (at 8,4,6 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.class_1949.method_8670(class_1949.java:84)
	at net.minecraft.class_3218.method_18765(class_3218.java:357)

-- Affected level --
Details:
	All players: 1 total; [class_3222['MSandro'/23, l='ServerLevel[1]', x=-7.70, y=64.00, z=7.47]]
	Chunk stats: ServerChunkCache: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,67,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 99661 game time, 63525 day time
	Level name: 1
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 81657 (now: false), thunder time: 15061 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7681/2096723395.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 783593088 bytes (747 MB) / 2782396416 bytes (2653 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		ae2wtlib: AE2WTLib 1.2.1-beta
		amecsapi: Amecs API 1.1.4+mc1.16.5
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.3.0-alpha.3
		architectury: Architectury 1.17.21
		authme: Auth Me 1.4.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		blockshifter: Blockshifter 1.3.2+fabric-1.16.4
		blue_endless_jankson: jankson 1.2.0
		breakprogress: Break Progress 1.0.1
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		cardinal-components: Cardinal Components API 2.8.2
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.2
		cardinal-components-level: Cardinal Components API (world saves) 2.8.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.2
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.2
		carrier: Carrier 1.7.6
		chainmail: Chainmail 0.5.0
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config2: Cloth Config v4 4.11.26
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_github_nathanpb_safer: Safer 1.1.0
		compressedblocks: Compressed Blocks 1.0
		controlling: Controlling For Fabric 1.1.2
		crookedcrooks: Crooked Crooks 1.3.3+1.16.4
		dankstorage: Dank Storage 1.10a-1.16.5
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.3-beta1
		expandedstorage: ExpandedStorage 5.6.33
		extragenerators: Extra Generators 1.0.1-BETA
		fabric: Fabric API 0.35.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+84310a227d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+0ef801b67d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 0.2.2+3185237c7d
		fabricloader: Fabric Loader 0.11.3
		fasttransferlib: Fast Transfer Lib 0.4.2
		fiber: fiber 0.23.0-2
		ftbchunks: FTB Chunks 1605.3.1-build.12
		ftblibrary: FTB Library 1605.3.1-build.18
		ftbteams: FTB Teams 1605.2.1-build.8
		ftbultimine: FTB Ultimine 1605.2.2-build.4
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.9.17-BETA
		inventorysorter: Inventory Sorter 1.7.9-1.16
		iron-jetpacks: Iron Jetpacks 0.3.1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jumploader: Jumploader 2.1.3
		kibe: Kibe 1.7-BETA
		ktdatataglib: KtDataTagLib 1.4.0
		kubejs: KubeJS 1605.3.10-build.23
		kyrptconfig: Kytpt Config 1.1.6-1.16
		libblockattributes: LibBlockAttributes 0.8.8
		libblockattributes_core: LibBlockAttributes (Core) 0.8.8
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.8
		libblockattributes_items: LibBlockAttributes (Items) 0.8.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		magna: Magna 1.5.1-1.16.5
		mcdict: MCDict 2.0.1+1.16.4
		megane: megane 4.1.3
		megane-applied-energistics-2: megane-applied-energistics-2 4.1.3+8.3.0-alpha.1
		megane-base: megane-base 4.1.3
		megane-fast-transfer-lib: megane-fast-transfer-lib 4.1.3+0.3.1
		megane-industrial-revolution: megane-industrial-revolution 4.1.3+1.8.13-BETA
		megane-kibe: megane-kibe 4.1.3+1.6.6-BETA
		megane-lib-block-attributes: megane-lib-block-attributes 4.1.3+0.8.7
		megane-modern-industrialization-4: megane-modern-industrialization-4 4.1.3+0.4.0-alpha.07
		megane-runtime: megane-runtime 4.1.3
		megane-team-reborn-energy: megane-team-reborn-energy 4.1.3+0.1.0
		megane-tech-reborn: megane-tech-reborn 4.1.3+3.8.2-build.220
		megane-vanilla: megane-vanilla 4.1.3+1.16.5
		minecraft: Minecraft 1.16.5
		modern_industrialization: Modern Industrialization 0.4.0-alpha.10
		mousewheelie: Mouse Wheelie 1.7.3+mc1.16.5
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		patchouli: Patchouli 1.16.4-50-FABRIC
		playerabilitylib: Pal 1.2.2
		pling: Pling 1.3.0
		reborncore: Reborn Core 4.7.3+build.136
		rhino: Rhino 1605.1.1-build.12
		roughlyenoughitems: Roughly Enough Items 5.12.248
		roughlyenoughitems-api: REI (API) 5.12.248
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.248
		roughlyenoughitems-runtime: REI (Runtime) 5.12.248
		scf: Super Cobblestone Funnels 1.2
		schmucks: Schmucks 1.3.2
		skyutils: Sky utilities Mod 1.0.1
		staffofbuilding: Staff of Building 1.2.6-1.16.5
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structureworld: Structure World 1.1.1-BETA
		tatters: Tatters 0.0.3+1.16
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.4+build.236
		trapexpansion: Trap Expansion 1.3.2
		tweed: Tweed 3.0.0-beta.26
		vanilladeathchest: VanillaDeathChest 2.0.6-fabric
		woodenhoppers: Wooden Hoppers 1.0.0
		wthit: wthit 2.10.2
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['MSandro'/23, l='ServerLevel[1]', x=-7.70, y=64.00, z=7.47]]
	Data Packs: vanilla (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by StellaBiscuit** [comment]
Did you modify the ore config? Because I've realised that if you add a blank line OR a line with a spelling mistake in the id, it WILL cause an out of bound crash

So check if there is a blank line at the end of the file

I think some sort of protection to both skip empty line and ignore bad id name would be a good idea
